name: XpBottles
main: me.codedred.xpbottles.Main
# Author set to 'Cmaaxx' for Metric purposes.
author: Cmaaxx
authors: [CodedRed, Cmaaxx]
version: 1.3.2
api-version: 1.16
loadbefore: [Essentials]
softdepend: [Vault]

commands:
  exp:
    description: Allows you to withdraw exp into an exp bottle!
    usage: /Exp
  xp:
    description: Allows you to use admin exp commands!
    usage: /Xp

  